name: Tests Script
run-name: Tests Script Actions
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '18'
      - run: npm ci
        name: clean install dependencies
      - run: npm run lint
        name: check eslint
      - run: npm test
        name: run unit tests
